language: python
python:
  - "3.7"
install:
  - pip install coveralls
  - pip install -r requirements.txt
script: 
  - coverage run -m tests.test_app
after_success:
  - coverage report
  - coveralls
notifications:
  slack: cyborged:37K3wQ7qoWjZ1FM2cf7TdJTC