"""empty message

Revision ID: 1c581a07c81f
Revises:
Create Date: 2019-11-25 14:58:22.016437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1c581a07c81f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog",
        sa.Column("description_token", postgresql.TSVECTOR(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog", "description_token")
    # ### end Alembic commands ###
